import { StyleSheet, Dimensions } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8F9FB",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  logoRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  miniIcon: {
    width: 30,
    height: 30,
    marginRight: 8,
  },
  miniLogoText: {
    width: 100,
    height: 25,
    resizeMode: "contain",
  },
  notificationBtn: {
    padding: 10,
    backgroundColor: "white",
    borderRadius: 20,
    elevation: 4,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  titleSection: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    marginBottom: 10,
  },
  mainTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#1A1A1A",
  },
  subTitle: {
    fontSize: 14,
    color: "#666",
    lineHeight: 20,
  },
  mascotSmall: {
    width: 70,
    height: 70,
  },
  searchContainer: {
    paddingHorizontal: 20,
    marginBottom: 15,
  },
  searchBar: {
    flexDirection: "row",
    backgroundColor: "white",
    borderRadius: 15,
    paddingHorizontal: 15,
    alignItems: "center",
    height: 55,
    elevation: 5,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  searchIcon: {
    fontSize: 18,
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: "#333",
  },
  filterBtn: {
    padding: 5,
  },
  mapWrapper: {
    flex: 1,
    marginHorizontal: 15,
    borderRadius: 30,
    overflow: "hidden",
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#EEE",
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  categoriesOverlay: {
    position: "absolute",
    bottom: 15,
    left: 0,
    right: 0,
    paddingLeft: 15,
  },
  chip: {
    flexDirection: "row",
    backgroundColor: "white",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
    alignItems: "center",
    elevation: 4,
    shadowColor: "#000",
    shadowOpacity: 0.1,
  },
  chipText: {
    marginLeft: 5,
    fontWeight: "600",
    fontSize: 12,
  },
  customMarker: {
    backgroundColor: "#6A1B9A",
    padding: 6,
    borderRadius: 15,
    borderWidth: 2,
    borderColor: "white",
    elevation: 5,
  },
  infoCard: {
    position: "absolute",
    bottom: 95,
    left: 20,
    right: 20,
    backgroundColor: "white",
    borderRadius: 25,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    elevation: 12,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 15,
  },
  locationImg: {
    width: 85,
    height: 85,
    borderRadius: 18,
  },
  infoDetails: {
    flex: 1,
    marginLeft: 12,
  },
  closestTag: {
    color: "#6A1B9A",
    fontSize: 10,
    fontWeight: "bold",
    textTransform: "uppercase",
  },
  locationTitle: {
    fontSize: 16,
    fontWeight: "bold",
  },
  iconRow: {
    marginVertical: 2,
  },
  locationItems: {
    fontSize: 11,
    color: "#777",
  },
  openStatus: {
    fontSize: 11,
    color: "#4CAF50",
    fontWeight: "600",
  },
  arrowBtn: {
    backgroundColor: "#6A1B9A",
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
  },
  bottomTab: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "white",
    paddingVertical: 12,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 20,
  },
  tabItem: {
    alignItems: "center",
  },
  tabIcon: {
    fontSize: 22,
    color: "#BBB",
  },
  tabLabel: {
    fontSize: 10,
    color: "#BBB",
    marginTop: 3,
  },
});
